language: python

python:
    - 3.6

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.7.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.7.1.deb && sudo service elasticsearch start

script:
  - while ! nc -z 127.0.0.1 9200; do sleep 1; done;
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install codecov==2.0.9

  - mkdir -p travis/codecoverage
  - flake8 .
  - black --check .
  - pytest
  - coverage xml -o coverage.xml

after_success:
  - codecov -t 8467f17f-e0d1-429d-93f6-8336ccab8248
